---
ID: "d18c6ba3-cd7f-5c3e-a238-ef32163b60b2"
Parent: "fe0b89fc-235e-5a00-bc40-0d2289f9ea67"
Template: "fe0b89fc-235e-5a00-bc40-0d2289f9ea67"
Path: "/sitecore/templates/Project/urlmapper-jss-app/Styleguide-FieldUsage-File/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191231T071518Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
