---
ID: "6e05b1b3-e12d-52c4-a619-b700fb719fcb"
Parent: "6ad47708-45d0-5765-a1ad-83ac3630b2d9"
Template: "6ad47708-45d0-5765-a1ad-83ac3630b2d9"
Path: "/sitecore/templates/Project/urlmapper-jss-app/Styleguide-Section/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191231T071520Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
