---
ID: "fbd0c558-cc3d-429b-9d40-2c4d82d16c08"
Parent: "096f42e6-cc9b-452c-8033-5cfefaf80536"
Template: "096f42e6-cc9b-452c-8033-5cfefaf80536"
Path: /sitecore/templates/Modules/UrlMapper2/_Shared Redirect/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191227T073103Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
