---
ID: "1c6c9387-cc86-46e4-b072-92e2dcd59cc9"
Parent: "c8a9de16-83cb-42d9-b691-173cd27dddaf"
Template: "c8a9de16-83cb-42d9-b691-173cd27dddaf"
Path: /sitecore/templates/Modules/UrlMapper2/_Redirect/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191227T073510Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
