---
ID: "255b1a09-da5c-43d9-a5d9-5c716278d07f"
Parent: "c8a9de16-83cb-42d9-b691-173cd27dddaf"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Modules/UrlMapper2/_Redirect/Redirect Configuration
DB: master
Languages:
- Language: "de-CH"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200120T085247Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191227T073535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
