---
ID: "8f9300a0-50d3-57bd-9991-793bfddf3728"
Parent: "f61e8670-4d1d-5b74-a0fa-31d8df2d95cd"
Template: "f61e8670-4d1d-5b74-a0fa-31d8df2d95cd"
Path: "/sitecore/templates/Project/urlmapper-jss-app/Styleguide-FieldUsage-RichText/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191231T071519Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
