---
ID: "57d61a02-8171-5cc3-a097-21c0e1481b82"
Parent: "e0fcc22b-11c6-5873-979a-43f4fc8f7cf2"
Template: "e0fcc22b-11c6-5873-979a-43f4fc8f7cf2"
Path: "/sitecore/templates/Project/urlmapper-jss-app/Styleguide-FieldUsage-Text/__Standard Values"
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20191231T071519Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
