name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    workflow_dispatch:  # 👈 allows manual trigger
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker-compose build

    - name: Tag Docker image
      run: docker tag sitecore-url-mapper yourdockerhubusername/sitecore-url-mapper:latest

    - name: Push Docker image
      run: docker push yourdockerhubusername/sitecore-url-mapper:latest
