name: Build and Push Docker Image

on:
  workflow_dispatch:  # 👈 allows manual trigger
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: docker login -u alainlehmann -p dckr_pat_YniXR3oBo3FfKc1KhDQcq9YUu30

    - name: Build with Docker Compose
      run: docker compose build
